# -*- coding: utf-8 -*-
"""Pomysły 2001-2300: ZAW / TRE / ADM / SUP — po 75 sztuk."""
from pathlib import Path

zaw = [
    "Jedno miejsce „Mój tydzień”: plan + starty + składka + czat — bez przeklikiwania modułów.",
    "Powiadomienie gdy trener zatwierdzi / odrzuci wynik lub ćwiczenie dodatkowe — z powodem w powiadomieniu.",
    "Eksport „moja karta startów” do PDF (data, miasto, kategoria) — do trenera lub lekarza.",
    "Ulubione ćwiczenia w planie — pin na górze listy jednostek.",
    "Własny cel sezonu (np. total / Sinclair) z paskiem postępu na dashboardzie zawodnika.",
    "Przypomnienie o uzupełnieniu masy ciała przed ważeniem — jeśli w profilu brak aktualnej.",
    "Porównanie z średnią klubu w kategorii (anonimowo z agregatu) — motywacja bez nazwisk.",
    "Historia wagowań i kategorii — oś czasu dla ważeń oficjalnych i samodzielnych wpisów.",
    "Tryb „tylko moje powiadomienia ważne” — filtr typów (wynik, składka, czat, klub).",
    "Szybki wpis treningu z szablonów (np. „klasyk Śr”: rozgrzewka + rwanie techniczne).",
    "Integracja z kalendarzem osobistym — jednym klikiem dodaj start z systemu do Google/Apple Calendar.",
    "Badge „trening zrobiony” po potwierdzeniu jednostki planu — mikro-nagroda / streak.",
    "Lista kontrolna przedstartowa (sprzęt, dokumenty, waga) — checklist na dzień przed zawodami.",
    "Udostępnij trenerowi link do nagrania techniki (YouTube unlisted / Drive) z poziomu profilu.",
    "Statystyki osobiste: ile treningów w miesiącu, średni RPE, dni przerwy.",
    "Powiadomienie gdy pojawi się nowy wpis w dzienniku od trenera (notatka do przeczytania).",
    "Filtr osi czasu: tylko zawody / tylko treningi / tylko obecności.",
    "Widok „co dalej w planie” — następne 3 jednostki z planu na jednym ekranie mobilnym.",
    "Przypomnienie o złożeniu deklaracji startowej jeśli klub zbiera deklaracje w systemie.",
    "Mini-kalkulator „ile muszę zabrać na sztangę” wg planu tygodnia (suma zaplanowanych %).",
    "Ulubione filmy techniki z biblioteki klubu — osobista playlista.",
    "Status kontuzji / ograniczeń widoczny tylko dla trenera i zawodnika (pole opcjonalne).",
    "Porównanie tygodnia z poprzednim: objętość, liczba sesji, najcięższe serie.",
    "Jasny komunikat gdy konto ma zaległą składkę — link do historii płatności.",
    "Tryb dyskretny na sali: większe przyciski, mniej tekstu, ekran nie gasnie podczas timera przerwy.",
    "Eksport dziennika treningów na miesiąc do CSV dla własnych analiz (Excel).",
    "Powiadomienie gdy zmieni się godzina lub miejsce treningu klubowego w kalendarzu.",
    "„Moi trenerzy” — lista kontaktów z rolami (główny / pomocniczy) z przyciskiem czatu.",
    "Powiązanie wyniku ze zdjęciem z medalami / podium — opcjonalna galeria osobista.",
    "Przypomnienie o uzupełnieniu ankiety regeneracji po ciężkim tygodniu.",
    "Widget z najbliższym startem na stronie głównej panelu zawodnika (data odliczania).",
    "Tryb czytania ogłoszeń bez oznaczania przeczytanych (preview).",
    "Szybki dostęp do regulaminu startów z karty zawodów (PDF/link).",
    "Powiadomienie gdy ranking publiczny zmieni pozycję zawodnika (opcjonalnie, rzadko).",
    "Ulubione ćwiczenia dodatkowe — szybkie dodawanie do kolejki zgłoszeń.",
    "Wyświetlanie limitów PR wg kategorii wagowej na podstawie profilu.",
    "Integracja: skopiuj adres hali do map — jeden tap z karty startu.",
    "Harmonogram snu sugerowany przed zawodami (edukacja, nie zamiast lekarza).",
    "Powiadomienie gdy trener doda komentarz do wpisu w dzienniku.",
    "Tryb „pierwszy raz na zawodach” — uproszczony checklist i poradnik w panelu.",
    "Udostępnianie osiągnięć (badges) jako grafika do social — z marką klubu.",
    "Filtr powiadomień: tylko od trenera / tylko klub / tylko system.",
    "Powiadomienie o zbliżającym się końcu ważności badania lekarskiego (jeśli data w profilu).",
    "Szablon wiadomości do trenera: „prośba o konsultację techniki”, „zmiana planu”.",
    "Wykres mood / samopoczucia 1–5 po treningach (opcjonalny, prywatny dla trenera).",
    "Powiadomienie gdy plan treningowy zostanie zaktualizowany — diff „co się zmieniło”.",
    "Lista „rzeczy do zrobienia” integrująca składkę, dokumenty, nieprzeczytane czaty.",
    "Szybki podgląd Sinclair na żywo przy wpisywaniu wagi i wyniku w kalkulatorze.",
    "Powiadomienie gdy inny zawodnik z grupy treningowej zrobi PR (jeśli klub włączy social).",
    "Tryb offline: podgląd ostatnio pobranego planu i listy startów.",
    "Powiązanie treningu z playlistą muzyczną (link Spotify) — osobiste, niepubliczne.",
    "Eksport „raport miesiąca” PDF: treningi, starty, składki, powiadomienia.",
    "Powiadomienie gdy składka zostanie zaksięgowana — potwierdzenie wpłaty.",
    "Ulubione strony w menu „Więcej” — konfigurowalny dock skrótów.",
    "Przypomnienie o szczepieniu / badaniu jeśli klub prowadzi pole obowiązkowe.",
    "Tryb dużej czcionki tylko w module plan/dziennik — bez psucia całego UI.",
    "Powiadomienie gdy trener oznaczy wpis jako „pilne” w czacie.",
    "Porównanie z poprzednim sezonem: najlepszy total, liczba startów.",
    "Powiadomienie gdy pojawi się nowy post w aktualnościach oznaczony jako ważny.",
    "Szybki dostęp do numerów alarmowych klubu i adresu hali z panelu.",
    "Powiadomienie gdy zgłoszenie ćwiczenia dodatkowego przejdzie w kolejce pozycję.",
    "Ulubione filtry na liście startów (np. tylko MP, tylko liga).",
    "Powiadomienie gdy regeneracja (sen) spada poniżej progu ustawionego z trenerem.",
    "Mini quiz techniczny tygodnia (edukacja) — bez wpływu na ranking.",
    "Powiadomienie gdy trening klubowy został odwołany lub przeniesiony.",
    "Własny podpis pod eksportowanym wynikiem (grafika) — imię + klub.",
    "Powiadomienie gdy limit miejsc na zapis zewnętrzny został osiągnięty (jeśli dotyczy).",
    "Tryb sesji na siłowni: ekran nie ściemnij + timer serii z wibracją.",
    "Powiadomienie gdy dokument klubu (np. regulamin członkowski) został zaktualizowany.",
    "Powiadomienie gdy odznaka zostanie odblokowana — gratulacje z share.",
    "Ulubione jednostki planu do powtórzenia jako szablon „własny microcykl”.",
    "Powiadomienie gdy czat trenera jest nieaktywny >7 dni — delikatna sugestia kontaktu.",
    "Własny cel tygodniowy objętości (kg×powtórzenia) z progress barem.",
    "Powiadomienie gdy planowany start został usunięty z kalendarza przez kadre.",
    "Szybki widok „kto ze znajomych z klubu jedzie na te zawody” (jeśli zgoda RODO).",
]

tre = [
    "Dashboard „moja grupa”: lista zawodników z filtrem ryzyko / forma / składka.",
    "Masowe oznaczanie obecności na jednostce + eksport do CSV dla zarządu.",
    "Szablony komentarzy do dziennika (technika, rozgrzewka, mobilność) — jeden klik.",
    "Alerty: zawodnik bez treningu X dni, bez odpowiedzi w czacie, zaległa składka.",
    "Porównanie dwóch zawodników: wykresy Sinclair, frekwencja, plan vs wykonanie.",
    "Przypisanie „grupy treningowej” (A/B/C) — filtrowanie planów i komunikatów.",
    "Notatki prywatne trenera o zawodniku — niewidoczne dla zawodnika.",
    "Plan tygodnia widokiem siatki — kto który dzień ma jednostkę z planu.",
    "Import podpowiedzi technicznych z analizy sztangi do komentarza w dzienniku.",
    "Masowa wysyłka przypomnienia o składce do wybranej grupy.",
    "Wideokonsultacje: pole link do Zoom/Meet przy wpisie treningowym (integracja).",
    "Szablon planu „start za 4 tygodnie” — automatyczna struktura tygodni.",
    "Heatmapa obecności zawodnika vs średnia grupy — wykrywanie spadku.",
    "Szybki widok pending: wyniki, ćwiczenia dodatkowe, wpisy dziennika do sprawdzenia.",
    "Przypisywanie drugiego trenera jako współprowadzącego grupę (read/write).",
    "Eksport listy startowej klubu na zawody zewnętrzne — format dla sekretariatu.",
    "Makra żywieniowe / suplementacja jako pole szablonowe w planie (nie zamiast dietetyka).",
    "Powiadomienie gdy zawodnik zgłosi kontuzję w dzienniku — priorytet na liście.",
    "Widok kalendarza grupy: nakładanie startów wielu zawodników.",
    "Ocena techniki skala 1–5 przy komentarzu do nagrania — trendy w czasie.",
    "Szablony wiadomości masowych do grupy (max N dziennie anty-spam).",
    "Powiązanie planu z konkretnym cyklem zawodowym (np. Mistrzostwa Polski).",
    "Automatyczna sugestia deloadu po N tygodniach bez PR (informacyjnie).",
    "Panel „kto na sali dziś” — check-in treningowy jeśli klub używa obecności.",
    "Kopiowanie planu między zawodnikami z anonymizacją nazw jednostek.",
    "Tagi na zawodnikach (kadra młodzieżowa, senior, rekreacja) — raporty.",
    "Integracja: eksport treningu tygodnia do arkusza Google (jednorazowy OAuth).",
    "Priorytet kolejki rozmów — pilne od zawodników przed startem.",
    "Statystyki grupy: średni total, mediana frekwencji, odsetek zaległych składek.",
    "Szablon powiadomienia push do grupy przed ważeniem (trener akceptuje treść).",
    "Widok porównania planu vs wykonanie % dla całej grupy.",
    "Blokada edycji planu przez zawodnika — przełącznik per plan (tylko trener).",
    "Historia zmian planu z audytem — kto zmienił obciążenia.",
    "Rekomendacja obciążeń na podstawie RPE z poprzedniego tygodnia (sugestia, nie auto).",
    "Powiadomienie gdy zawodnik uzupełni ankietę regeneracji — podsumowanie na liście.",
    "Współdzielony folder materiałów (PDF) per grupa — tylko dla tej grupy.",
    "Tryb „obóz” — plan dzienny z godzinami i mapą sali (tekstowo).",
    "Masowe przypisanie wydarzenia kalendarzowego do grupy (np. zbiórka).",
    "Wykrywanie zawodników bez aktualnego badania — lista dla trenera.",
    "Komentarz głosowy do planu — nagranie max 2 min (jeśli backend pozwoli).",
    "Szablon startów sezonu — kopiowanie listy z ubiegłego roku z edycją.",
    "Powiadomienie gdy średnia grupy spadnie poniżej progu frekwencji.",
    "Integracja z tablicą wyników live wewnętrznych zawodów klubu.",
    "Przypisywanie zadań domowych (mobilność, rozciąganie) z potwierdzeniem przez zawodnika.",
    "Widok ryzyk: kontuzje + niskie RPE + zaległe składki na jednej kartce.",
    "Eksport PDF „raport grupy miesiąc” dla zarządu klubu.",
    "Powiadomienie gdy zawodnik doda film techniki — kolejka do obejrzenia.",
    "Szablony wiadomości do rodziców (jeśli niepełnoletni) — osobny kanał.",
    "Porównanie planów dwóch tygodni obok siebie (diff jednostek).",
    "Powiadomienie gdy limit obłożenia sali został osiągnięty (jeśli rezerwacje).",
    "Przypisywanie „poziomu” zawodnikom (początkujący/średni/elita) — filtrowanie treści.",
    "Automatyczna lista „kto potrzebuje feedbacku” po tygodniu bez komentarza trenera.",
    "Powiadomienie gdy zawodnik zmieni kategorię wagową w profilu.",
    "Wspólny kalendarz spotkań indywidualnych z integracją ICS.",
    "Szablon mikrocyklu 3:1 — jednym klikiem rozłożenie na grupę.",
    "Powiadomienie gdy średni czas odpowiedzi trenera w czacie przekroczy SLA (wewnętrznie).",
    "Widok „nadchodzące starty grupy” z możliwością eksportu dla busów.",
    "Przypisywanie celów grupowych (np. średnia frekwencja 80%).",
    "Powiadomienie gdy zawodnik oznaczy trening jako „za ciężki”.",
    "Biblioteka ćwiczeń z notatkami trenera widocznymi tylko dla grupy.",
    "Masowe oznaczenie przeczytanych powiadomień grupy (admin trenera).",
    "Powiadomienie gdy plan jest niekompletny (brak jednostki w tygodniu).",
    "Integracja z licznikiem tonazu grupy (suma tygodnia) — tablica motywacyjna.",
    "Szablon wiadomości po zawodach: gratulacje / debrief.",
    "Powiadomienie gdy zawodnik nie odda ankiety po zawodach.",
    "Widok „nowi w grupie” — pierwsze 30 dni osobnej uwagi checklist.",
    "Powiadomienie gdy średnia wieku grupy zmieni się (np. napływ juniorów).",
    "Raport „gotowość do startu” — checklist zawodnika X dni przed zawodami.",
    "Powiadomienie gdy trener drugi doda komentarz w planie (koordynacja).",
    "Ulubione metryki na dashboardzie trenera — konfiguracja widżetów.",
    "Powiadomienie gdy grupa przekroczy limit liczebności (jeśli klub ustawi).",
    "Wykres obciążenia tygodniowego grupy vs wybranego zawodnika — kontekst obciążeń.",
    "Powiadomienie zbiorcze: „grupa ukończyła plan tygodnia” — motywacja i widok postępu.",
    "Biblioteka mikrocykli: szczyt, tapering, po-zawodowy — szablony do przypięcia.",
    "Eksport „lista startowa po ważeniu” do PDF dla sekretariatu z jednym kliknięciem.",
]

adm = [
    "Panel „zdrowie klubu”: składki, aktywni zawodnicy, pending wyników na jednym ekranie.",
    "Masowe zaproszenia na konto e-mailem z szablonem klubu i linkiem aktywacyjnym.",
    "Szablony ogłoszeń (trening odwołany, zbiórka, zbiórka składek) — wersje PL/EN.",
    "Role z granularnymi uprawnieniami: kto może blog vs kto kalendarz vs kto płatności.",
    "Eksport członków do Excel z polami zgody marketingowej i statusu składki.",
    "Workflow zatwierdzania wydatków klubu (jeśli moduł finansów rozszerzony).",
    "Audit widoczny dla admina: ostatnie 50 akcji kadry bez wchodzenia w SuperAdmin.",
    "Harmonogram publikacji aktualności — zaplanowany post na datę.",
    "Lista kont zablokowanych z możliwością odblokowania i powodem bana.",
    "Import listy płatności bankowych CSV — dopasowanie po nazwisku (asystowane).",
    "Szablony maili systemowych edytowalne przez admina (nagłówek, stopka klubu).",
    "Podgląd jako zawodnik / jako trener — impersonacja read-only z audytem.",
    "Konfiguracja progów składki per rok i kategoria (junior/senior).",
    "Zarządzanie trenerami: przypisanie do grup i widoczność zawodników.",
    "Eksport statystyk klubu do PDF na walne zebranie.",
    "Powiadomienie admina gdy liczba pending wyników > próg.",
    "Szablony wydarzeń kalendarza (liga/mistrzostwa/trening stały) — jeden klik.",
    "Integracja z newsletterem (Mailchimp/Brevo) — segment aktywnych zawodników.",
    "Polityka haseł klubu: minimalna długość, wymuszenie resetu co X mies.",
    "Panel sponsorów: logo + link + kolejność wyświetlania na www.",
    "Zarządzanie treścią statyczną (adres, godziny, kontakt) bez deployu kodu.",
    "Lista „do zrobienia dla kadry” generowana automatycznie (składki, dokumenty).",
    "Powiadomienie gdy kończy się domena SSL lub integracja zewnętrzna (manual checklist).",
    "Szablony dokumentów klubu (oświadczenia, zgody) do pobrania z panelu.",
    "Przypisywanie adminów pomocniczych z zakresem tylko wybranych modułów.",
    "Raport frekwencji vs składki — korelacja dla zarządu (agregaty).",
    "Konfiguracja widoczności rankingu publicznego (ukryj juniorów / wagę).",
    "Masowe przypisanie roli Athlete po imporcie CSV.",
    "Powiadomienie gdy blog ma wpis w szkicu dłużej niż 14 dni.",
    "Eksport logów czatu tylko dla sądowych żądań — procedura i ZIP.",
    "Szablony powiadomień push klubowych z akceptacją dwóch adminów.",
    "Panel „zgłoszenia od mieszkańców” — formularz kontaktowy z tiketami.",
    "Konfiguracja limitów uploadu zdjęć i wideo dla użytkowników.",
    "Harmonogram czyszczenia kont nieaktywnych — polityka retencji.",
    "Powiadomienie gdy zbliża się koniec roku składkowego.",
    "Integracja z księgowością — eksport CSV dla biura rachunkowego.",
    "Szablony SMS (jeśli gateway) dla pilnych odwołań treningów.",
    "Zarządzanie wersjami regulaminu klubu — użytkownik musi zaakceptować nową.",
    "Statystyki wejść na www i konwersja „zapisz się” — podstawowa analityka.",
    "Powiadomienie gdy liczba nowych kont > próg dziennie (możliwy spam).",
    "Konfiguracja grup wiekowych dla zawodów wewnętrznych.",
    "Eksport listy obecności na zbiórkę dla sprawozdawczości związku.",
    "Szablony uprawnień „tylko odczyt” dla osoby od PR klubu.",
    "Powiadomienie gdy integracja Blob/storage zwraca błąd > N razy.",
    "Panel darowizn / wpłat celowych jeśli klub zbiera zbiórki.",
    "Konfiguracja treści stopki www (social, nip, regon) centralnie.",
    "Masowe oznaczenie przeczytanych ogłoszeń przez zawodników (test kampanii).",
    "Powiadomienie gdy termin licencji trenera w bazie się kończy.",
    "Szablony zgód RODO per proces (newsletter, zdjęcia na www).",
    "Integracja z Google Analytics / Plausible — ID w ustawieniach klubu.",
    "Raport „przychody składki vs plan” miesiąc do miesiąca.",
    "Powiadomienie gdy limit API zewnętrznego (np. mapy) się kończy.",
    "Konfiguracja barw klubu dla eksportów PDF i maili.",
    "Lista rezerwowa na zawody wewnętrzne z automatyczną kolejką.",
    "Powiadomienie gdy drużyna wyjeżdża na zgrupowanie — checklist wyjazdowy.",
    "Szablony dokumentów dla zawodów (program, lista startowa) generowane z systemu.",
    "Zarządzanie kontami rodziców powiązanych z nieletnimi.",
    "Powiadomienie gdy liczba zgłoszeń do zawodów przekroczyła limit sali.",
    "Konfiguracja widoku publicznego bloga (ukryj daty / pokaż autora).",
    "Eksport „członkowie aktywni” do integracji z CRM klubu.",
    "Powiadomienie gdy backup bazy nie został potwierdzony przez X dni (SuperAdmin może dublować).",
    "Szablony komunikatów o zamknięciu obiektu (śnieg, awaria).",
    "Koordynacja wolontariuszy na zawodach — lista kontaktów z poziomami dostępu.",
    "Powiadomienie gdy liczba postów blogowych spadła poniżej celu kwartalnego.",
    "Konfiguracja progów dla automatycznych przypomnień o składce (dzień miesiąca).",
    "Panel „zgody na zdjęcia” — zawodnicy którzy nie wyrazili zgody.",
    "Powiadomienie gdy umowa z dostawcą (np. hosting) jest w archive — odnowienie.",
    "Szablony harmonogramów treningów letnich vs zimowych.",
    "Zarządzanie kontami mediów — dostęp tylko do aktualności i galerii.",
    "Powiadomienie gdy zbliża się termin audytu związku dla klubu.",
    "Konfiguracja widoku rankingu (ukryj Sinclair / pokaż tylko total).",
    "Eksport listy „do kontaktu” po zebraniu — CSV telefonów (RODO).",
    "Powiadomienie gdy liczba zaległych składek > X% kadry.",
    "Szablony uchwał zarządu jako załączniki do komunikatów.",
    "Koordynacja wynajmu sali — kalendarz zajęć poza sekcją podnoszenia.",
]

sup = [
    "Globalny kill-switch funkcji eksperymentalnych z telemetrią aktywacji.",
    "Porównanie instancji preview vs production pod kątem migracji schema.",
    "Sandbox z anonimowym zrzutem struktury DB (bez PII) do debugowania.",
    "Panel quota API: zużycie Turso, Blob, egress — alerty progów.",
    "Symulacja obciążenia — skrypt k6 z zestawem krytycznych endpointów.",
    "Masowa migracja ról po zmianie modelu RBAC — raport konfliktów.",
    "Integracja z Sentry/DataDog — mapowanie release frontend/backend.",
    "Harmonogram rotacji sekretów (JWT, webhook HMAC) z checklistą.",
    "Podgląd różnic konfiguracji env między środowiskami (redacted).",
    "Narzędzie czyszczenia duplikatów zawodników po imporcie historycznym.",
    "Panel „feature adoption”: ile kont używa modułu X w 30 dni.",
    "Automatyczny raport bezpieczeństwa: nagłówki CSP, cookies, HSTS.",
    "Dry-run migracji SQL na kopii bazy przed produkcją.",
    "Integracja z GitHub Dependabot — priorytety PR security.",
    "Lista tenantów (przyszłość multi-klub) — stub konfiguracji.",
    "Replay wybranych żądań API z logów (bez body PII) — diagnostyka.",
    "Konfiguracja globalnych limitów rate-limit per IP dla całej platformy.",
    "Backup verification job — sumy kontrolne tabel krytycznych.",
    "Panel eksperymentów ML — wersje modeli TensorFlow / MediaPipe.",
    "Masowe unban z audytem i powodem — odwrotność bana.",
    "Integracja z OIDC dla kadry IT klubu (opcjonalny SSO).",
    "Symulacja kosztów Blob przy prognozie rozrostu mediów.",
    "Narzędzie eksportu całego klubu do ZIP (GDPR data portability super).",
    "Porównanie wersji OpenAPI — breaking changes w CI.",
    "Panel „incidents”: historia alertów i czasów naprawy.",
    "Konfiguracja globalnych komunikatów banerowych (maintenance window).",
    "Test penetracyjny checklist OWASP Top 10 — ticket template.",
    "Shard routing preview — przygotowanie pod skalowanie horyzontalne.",
    "Integracja z PagerDuty/Opsgenie dla alertów backend 5xx.",
    "Narzędzie anonymizacji staging dump przed udostępnieniem devom.",
    "Panel „wersje mobilki”: minimalna wspierana vs najczęstsza w logach.",
    "Automatyczne zamrażanie kont nieaktywnych >2 lat — polityka.",
    "Konfiguracja globalnych CORS origins — walidacja przy deployu.",
    "Replay worker kolejek — ponów failed jobs z limitem.",
    "Integracja z Vault dla sekretów zamiast samych env (roadmap).",
    "Dashboard kosztów Vercel vs transfer — optymalizacja assetów.",
    "Narzędzie merge kont użytkowników po duplikacie email.",
    "Globalny szablon polityki prywatności z polem wypełnianym per klub.",
    "Test chaos na staging — wyłączenie jednej repliki API.",
    "Panel „mapa tras” zsynchronizowany z routerem i middleware.",
    "Konfiguracja sink logów (CloudWatch/Datadog) jednym JSON.",
    "Walidator JSON payloadów z produkcji vs schema — nightly.",
    "Integracja z Stripe invoices dla przychodów platformy (jeśli SaaS).",
    "Narzędzie czyszczenia starych tokenów push nieaktywnych urządzeń.",
    "Globalny feature flag „tryb zawody” — wyższy rate limit dla live.",
    "Symulacja failover Turso — procedura runbook jednostronicowa.",
    "Panel „wersje Rust”: lista crate z CVE z cargo audit.",
    "Masowy export audit logów do zewnętrznego SIEM (webhook).",
    "Konfiguracja minimalnej wersji aplikacji mobilnej — force update.",
    "Narzędzie porównania dwóch snapshotów bazy (checksum per table).",
    "Integracja z Terraform plan preview w PR infrastruktury.",
    "Panel „limity uploadów” globalnie vs per klub.",
    "Automatyczne ticketowanie gdy error rate endpointu > próg 15 min.",
    "Konfiguracja IP allowlist dla endpointów superadmin tylko z VPN.",
    "Narzędzie seedowania danych demo dla targów i szkoleń.",
    "Globalny registry webhooków partnerów — rotacja kluczy.",
    "Porównanie bundle size frontend między release — regresja KB.",
    "Panel „health dependency”: status zewnętrznych API (PZPC itd.).",
    "Konfiguracja retention audit logów vs RODO minimalny okres.",
    "Narzędzie podziału monorepo na release notes per pakiet.",
    "Integracja z Linear/Jira — tworzenie ticketów z alertów.",
    "Symulacja latencji Sieci 3G dla testów mobilnych API.",
    "Panel „czarna lista IP” po ataku brute-force globalnie.",
    "Konfiguracja dual-write przy migracji kolumny krytycznej.",
    "Narzędzie approval chain dla migracji DB — dwóch reviewerów.",
    "Integracja z SonarCloud dla jakości kodu frontend/backend.",
    "Globalny harmonogram maintenance — komunikat we wszystkich panelach.",
    "Panel „wersje Node/Rust” na serwerze build vs lokalnie.",
    "Automatyczne zamykanie kont testowych po 24h.",
    "Konfiguracja max rozmiaru czatu attachment globalnie.",
    "Narzędzie porównania odpowiedzi API prod vs staging dla tego samego ID.",
    "Integracja z Statuspage dla komunikatów przy incydencie.",
    "Symulacja shardingu po athlete_id — eksperyment przyszłościowy.",
    "Panel „koszt workerów” CPU czasu dla cronów.",
    "Konfiguracja globalnego CAPTCHA threshold przy podejrzanym ruchu.",
]

assert len(zaw) == len(tre) == len(adm) == len(sup) == 75

lines = []
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Pomysły funkcji wg ról (ZAW · TRE · ADM · SUP) — numery 2001–2300")
lines.append("")
lines.append(
    "Priorytety pod **doświadczenie roli**: zawodnik (ZAW), trener (TRE), administrator klubu (ADM), SuperAdmin platformy (SUP). "
    "Można filtrować po prefiksie w wyszukiwarce pliku."
)
lines.append("")

lines.append("### Zawodnik (Athlete)")
lines.append("")
for i, text in enumerate(zaw, start=2001):
    lines.append(f"{i}. **ZAW — {text}**")

lines.append("")
lines.append("### Trener (Trainer)")
lines.append("")
for i, text in enumerate(tre, start=2076):
    lines.append(f"{i}. **TRE — {text}**")

lines.append("")
lines.append("### Administrator klubu (Admin)")
lines.append("")
for i, text in enumerate(adm, start=2151):
    lines.append(f"{i}. **ADM — {text}**")

lines.append("")
lines.append("### SuperAdmin (platforma)")
lines.append("")
for i, text in enumerate(sup, start=2226):
    lines.append(f"{i}. **SUP — {text}**")

out = Path(__file__).resolve().parents[1] / ".ideas_roles_chunk.md"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"OK {out} lines={len(lines)}")
